### PR TITLE
Added mob repulsor and support files.

### PR DESCRIPTION
**Pull request by scottosx**
I am trying to separate each feature change into its own commit. However, there are some additions in lang file and items for fungus which I am still cleaning up before commit.
FYI, I just learned how to publish only 'hunks' of changes to files like the lang. Commits should be cleaner now. 12/4/16

On commit 'Removed colorizer source block consumption https://github.com/grim3212/Grim-Pack/pull/65/commits/a19414894bc315ee8a4f955fc936a86f04fdfbc2
 I have simply commented out the code that takes from player inventory and spawns in the world on breaking. This is to be sure there are no further implications and for easy reverting. If change is accepted will remove this code.

### CODE REVIEW

**Comment by grim3212** [comment]
I'll take a look at this after this week since it's finals. I have been extremely busy with school.

**Comment by scottosx** [comment]
It's cool. Good luck on finals. I have several more changes in the pipeline but hope not to put too many on you at once.

**Comment by grim3212** [comment]
So is everything stable in this? I am working on an update to 1.11 so I would like to update everything together.

EDIT:

Looking over everything and it all looks good.
As for the colorizer consumption you can leave the code commented. I might add that to a config option just for flexibility. I say that we give as many options as possible.

Also, the tameable treasure mob seems pretty cool. I am out of school for winter so I should be able to work on this again.

EDIT EDIT: 

Okay actually I will just merge and we can deal with problems later.

**Comment by grim3212** [comment]
So, I have merged but I realized that your pull request didn't include all the changes to fungus but about half of it.

**Comment by scottosx** [comment]
I will merge in my fungus changes which are mostly complete but I wanted to keep them as a separate project distinct from this commit for isolation.

**Pull request merged**
