### PR TITLE
Modern Furnace vanilla functions

### PR DESCRIPTION
**Pull request by scottosx**

### CODE REVIEW

**Comment by grim3212** [comment]
Okay so I may have caused this but the floating islands has already been added. I added it in weird so that's my fault. Also, I am fine with the changes to the furnace but I am wondering what the point of making fuel would be now that you can fuel it with any vanilla source.

**Comment by scottosx** [comment]
I did see the way you implemented Floating Islands and that is good, mine was a hack. However, SourceTree doesn't stop me pushing it. I think it is because I am not writing to master but to a fork.

GrimPack Fuel is essentially infinite (it seems) with a derrick. When you Silk Touch an Oil ore you can move it wherever you want. Otherwise, to lock the furnace into one fuel IMHO is a bad idea because people balance out those choices to choose which mod to use. Early game without oil they can still benefit from the modern furnace. That's my take on it.

**Comment by grim3212** [comment]
Oh okay I didn't think of it as basically infinite just annoying to convert to fuel. I'll get this merged. Also, I just pushed some 'hopefully' final logic changes to the slingshot for changing modes and getting the correct ammo type. So, if you wanted the damage values tweaked or something changed tell me.

**Comment by scottosx** [comment]
One thing we might want to look at is ore dictionary for oil. The Grim way of producing it is superior to many mods whose energy generation requires oil. Steel is ore dictionary and I use the Grim version in many recipes as it so much easier to automate.

Element 115 and all of our other ores need ore dictionary for automated mining as well.

Damage values:
	STONE(1.0F, "stone"), IRON(8.0F, "iron"), NETHERRACK(16.0F, "netherrack"), LIGHT(1.0F, "light"), FIRE(1.5F, "fire"), EXPLOSION(1.5F, "explosion");

What do you think about the idea of edible fungus? Like a superfood, well, not really with some balance but present as such. It would be like Jello or gelatin.

**Comment by grim3212** [comment]
I think the idea of edible fungus is a good idea and would make fungus more interesting.
I think stone is fine but for iron and netherrack it may be too high of damage. Probably around 6 for iron and 5 for netherrack. I know you have to go to the nether but there is so much I might be too strong. Possibly a config option?

As for the ore dictionary what would you recommend I oredict. Just the ore itself or the cans. Same for element115.

**Comment by scottosx** [comment]
Iron pellets are pretty expensive in resources, netherrack in game stage. But yeah, configurable is always better. I look at it like weapons have to be superior than vanilla or why bother? The slingshots do have a faster draw though.

Ore dictionary basically all of the ores I say. Other mods have randomite and black diamond too. Might as well really support as much as possible. A couple of super mods to look at if you haven't are Actually Additions which is cool and getting a big push from DireWolf20 and Cyclic which has a lot of nifty machines and buffs like we do.

I think it would be funny to have different recipes for edible fungus with increasing nutrition values. Like straight fungus say 1HP, mixed with bonemeal to make gelatin for 2HP, or bones for 3HP. The funny part is gelatin is made from cartilage but people don't like to think about that. Also, for 4HP you could add fruit to it. Thoughts?

**Comment by grim3212** [comment]
Alright I will get around to that.

Also, I am totally for the edible it sounds like a cool idea and I have been meaning to add more things to cuisine as well as have some crossover between the parts. Hits two birds with one stone.

**Pull request merged**
