### PR TITLE
Furnace and Refinery Transmutations

### PR DESCRIPTION
**Pull request by scottosx**
Test for collaboration. Left commented code in to revise.

Should be in full sync with master now.

### CODE REVIEW

**Comment by scottosx** [comment]
I was thinking about creating a transmutation to make bedrock. The bedrock texture looks good on sloped roofs. The problem of course is that is unbreakable unless you change the option in the config. Thoughts on that and suggested precursor?

**Comment by grim3212** [comment]
Possibly bedrock texture on a new block. Or a brush but instead of clearing can give out the bedrock texture. There would need to be a lot of special cases done to ensure that the blocks don't drop though.

**Comment by scottosx** [comment]
The thing about creating the actual bedrock block is that you don't have to place it down to do what I am intending it for, which is texture a colorizer. Only have it in your hand.

**Comment by grim3212** [comment]
Well that's why a brush could work. It's not a block but would allow for texturing of the colorizers.

**Comment by scottosx** [comment]
I don't know about brushes yet. Haven't played with them. What do they do? I thought there was just a small selection of colored brushes.

**Comment by grim3212** [comment]
Well I was more talking about it would be similar to the brush that can clear textures from colorizers.

**Comment by scottosx** [comment]
I see. Texture coloring brushes would be cool.

**Comment by scottosx** [comment]
How come blocks like the halogen lights and camo plates can't be placed on colorizers?

**Comment by grim3212** [comment]
Technically Colorizer blocks are not full blocks.

**Comment by scottosx** [comment]
I see. How would effect say colorized chests? Which are not full blocks either?

**Comment by grim3212** [comment]
Nothing would need to be changed. Colorizer is like that just so that all of the blocks that extend it don't have to implement it but it wouldn't be that difficult just moving some methods around.

**Comment by scottosx** [comment]
Colorized doors would be nice too but they like fence gates can only be opened with an empty hand or item which can't pass the texture. One thing about them too, in my 1.8.9 world they JEI list was filled with every possible combination of colorized blocks and of course was huge. 1.10.2 doesn't do that. Or maybe it was an addon that did it.

**Comment by grim3212** [comment]
Yeah that was because in 1.10 I completely rewrote how they work to be more flexible. Also, after they are colorized in survival you can still open fence gates with blocks. It's only if they are untextured.

**Comment by scottosx** [comment]
Ok, that is good. I am testing in creative. Planning another video. I am building a whole house out of colorizers to show how it expands your design choices and also you to change up easily when you get bored with the texture. Next I will test if the new structure block works with them.

**Comment by scottosx** [comment]
Do counters suffer the same not full block issue? For instance I cannot place flower pots on them. But I can place heads.

**Comment by scottosx** [comment]
Colorized flower pots would be great too as well as heads. Heads are flexible because the ability to change orientation. Can you tell that I think Colorizers are one of the best parts of the mod? I am sure many agree and those that don't know would install GrimPack for that alone.

**Comment by grim3212** [comment]
Yeah it is my favorite part too. Also, there might be a method that allows for things to be placed on top of blocks. That's how I am able to place torches on Fences.

**Comment by scottosx** [comment]
Colorized wall paper too. I like the wallpaper and will make some more textures at some point. But using it as a colorizer would allow you to have different pseudo textures on block faces. As I said colorized doors would be neat because they could completely blend in and hide themselves.

**Comment by scottosx** [comment]
Another cool colorized thing would be the interior (background) of flat frames.

**Comment by grim3212** [comment]
Yeah colorizer's have so many options. It just takes time to get everything working for them.

**Comment by scottosx** [comment]
In the manual you say that stools look great with clay pots placed on them. But flower pots don't work. What clay pots do you mean?

**Comment by grim3212** [comment]
The pots that are included in Decor.

**Pull request merged**
